version: "3"

services:
  db:
    image: postgres:15.2
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
      POSTGRES_HOST: localhost
      POSTGRES_PORT: 5432
  client: 
    build: 
      context: ./app/client
      dockerfile: Dockerfile
    restart: always
    ports:
      - "3000:3000"
  server:
    build: 
      context: ./app/server
      dockerfile: Dockerfile
    restart: always
    ports:
      - "8000:8000"
    depends_on:
      - db

